version: '3.3'

volumes:
  db_value:
  static_value:
  media_value:
  frontend_value:

services:

  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    image: karinarin/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    image: karinarin/foodgram_backend:latest
    volumes:
      - frontend_value:../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend